[08/10/2022-16:10:05] [TRT] [E] 3: [layers.cpp::validateEquation::5856] Error Code 3: Internal Error ((Unnamed Layer* 0) [Einsum]: Diagonal operations are not permitted in Einsum equation)
Traceback (most recent call last):
  File "./EinsumLayer/Diagonal.py", line 36, in <module>
    network.mark_output(einsumLayer.get_output(0))
AttributeError: 'NoneType' object has no attribute 'get_output'
